### ISSUE TITLE
adding cmd and msglvl

### ISSUE THREAD

**Issue by minghuadev** [safchain/ethtool#1]
hi, thanks for sharing the nice code. can I suggest some enhancement to add two commands/calls? the diff to ethtool.go and 4 additional files are attached. feel free to use or tailor as you see that suits. 

sorry github only allows certain file types. all the file names are suffixed by .txt . 

[ethtool.go-diff.txt](https://github.com/safchain/ethtool/files/509972/ethtool.go-diff.txt)
[ethtool_cmd.go.txt](https://github.com/safchain/ethtool/files/509968/ethtool_cmd.go.txt)
[ethtool_cmd_test.go.txt](https://github.com/safchain/ethtool/files/509971/ethtool_cmd_test.go.txt)
[ethtool_msglvl.go.txt](https://github.com/safchain/ethtool/files/509969/ethtool_msglvl.go.txt)
[ethtool_msglvl_test.go.txt](https://github.com/safchain/ethtool/files/509970/ethtool_msglvl_test.go.txt)

**Comment by safchain** [comment]
Hi, looks good, thx for the enhancements. Maybe you could send a pull request so that the reviewing process will be easier and  you will be seen as contributor.

**Comment by minghuadev** [comment]
sent #7 which passed the travis test.
