### ISSUE TITLE
support geting link state

### ISSUE THREAD

**Issue by zshi-redhat** [safchain/ethtool#17]
Do we support getting link state via ethtool? if not, is it worth adding to detect the link state changes of network device?

	Supported ports: [ ]
	Supported link modes:   10000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  Not reported
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: 10000Mb/s
	Duplex: Full
	Port: Other
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes               <==========================

**Comment by dcbw** [comment]
@zshi-redhat link detection is usually done by netlink these days, via IFF_LOWER_UP. The ethtool kernel code just checks that flag anyway. So perhaps just use vishvananda/netlink and check the interface flags?
