### ISSUE TITLE
const MAX_GSTRINGS = 100 limit

### ISSUE THREAD

**Issue by Comradin** [safchain/ethtool#2]
Hello,

less an issue than more a question:
https://github.com/safchain/ethtool/blob/master/ethtool.go#L54-L58

These lines limit the number of entries in the Stats() call to 100 entries. I am currently working with Solarflare cards that will return 129 entries and the Stats() call will panic.

Is it safe to raise the limit or will the code fail in other ways when I raise it?
I did a quick test with a value of 192 and got a result from my network card, but there is some bad feeling.

Kind regards,
Marcus

**Comment by safchain** [comment]
Hello,

I do not see any issue with increasing this value. Feel free to send a PR.

Regards
Sylvain

**Comment by Comradin** [comment]
Thanks for merging the PR.
