### ISSUE TITLE
Increase MAX_GSTRINGS to support more stats

### ISSUE THREAD

**Issue by danielnelson** [safchain/ethtool#29]
In Telegraf we are running into the `MAX_GSTRINGS` limit when reading stats.  Currently the MAX_GSTRINGS is set to 100, and I see it was bumped up in #2 several years back from 100.

The NIC we are having issues has about 2480 stats according to `ethtool -S`.  Do you think it would it make sense to further increase this limit?
 
https://github.com/influxdata/telegraf/issues/6913

**Comment by safchain** [comment]
@danielnelson yes feel free to send a PR to increase it if needed

**Comment by ykuksenko** [comment]
This was bumped to 4096 in #28  
Someone asked to bump this to 8192 shortly after.
